### ISSUE TITLE
Bug on 32bit machines

### ISSUE THREAD

**Issue by BrunoDutertre** [arminbiere/cadical#10]
Make test fails on 32bit machines:
```
test/usage/run.sh: running usage test 'test-usage-O1-prime2209'
../build/cadical  -O1 ../test/cnf/prime2209.cnf # FAILED (unexpected exit code '20')
```
This can be fixed by changing size_t to uint64_t in analyze_trail_negative_rank
(in analyze.cpp).

**Comment by arminbiere** [comment]
Sorry, CaDiCaL ist not yet ready for 32 bit (nor Windows).  This is the next 'clean up' work after removing the Cish memory allocator but with unknown ETA.

**Comment by DvonHolten** [comment]
i could build the version downloaded from git on 2nd July with cygwin64 under win7x64, more or less out of the box.
Runtime for first try is reduced by 200 sec compared to the version of may 2018. 
Hmm - it's now 105 sec vs. 310 sec in previous version.
Gut gemacht - weiter so !

**Comment by arminbiere** [comment]
With version 1.0.3 we support also 32 bit builds using the '-m32' option to 'configure'.  This also triggers different compilation options for floating point computation (forces 64 instead of the default 80 bit for Intel).
