### ISSUE TITLE
Is there a reason why this sets the blocking literal to `other` rather than `lit`?

### ISSUE THREAD

**Issue by msoos** [arminbiere/cadical#103]
Hi Armin,

Is there a reason why this is not setting the blocking literal to `lit`? I am getting worse performance in another solver when this is `other`, rather than `lit`.

https://github.com/arminbiere/cadical/blob/2df7b7fed0f9c522fd4cdf6e88cecad4cac8a2df/src/propagate.cpp#L424

It may be best this way in CaDiCaL, but it seems a bit odd, given that in the other case, CaDiCaL is also setting `lit` rather than `other` as the blocking literal.

**Comment by m-fleury** [comment]
As far as I can see, this code is only used with `--chrono=2`, which is not the default value anyway.
