### ISSUE TITLE
LratBuilder::new_clause

### ISSUE THREAD

**Issue by baselkhouri** [arminbiere/cadical#107]
https://github.com/arminbiere/cadical/blob/2df7b7fed0f9c522fd4cdf6e88cecad4cac8a2df/src/lratbuilder.cpp#L55

Unless I have missed something, 'off' should be assigned to 1 (positive) if size > 0 in that case. Alternatively, (size + off).

const int off = size > 0 ? 1 : 0;

**Comment by m-fleury** [comment]
@florianpollitt we might want to have the NFLEXIBLE stuff in the builder too in the lrat builder.

**Comment by florianpollitt** [comment]
Thanks for spotting that!
