### ISSUE TITLE
Unclear meaning of `ccadical_val` return value

### ISSUE THREAD

**Issue by timvermeulen** [arminbiere/cadical#108]
I'd love some guidance to understand the meaning of the return value of `ccadical_val`, particularly when the argument is a negative literal.

`ccadical_val` calls `Solver::val`, which is documented as
https://github.com/arminbiere/cadical/blob/2df7b7fed0f9c522fd4cdf6e88cecad4cac8a2df/src/cadical.hpp#L289
but it seems as though its actual behavior is flipped in the case that `lit` is negative, i.e. `abs(lit)` is returned when `lit` is true, and `-abs(lit)` is returned when `lit` is false. I get the impression that this behavior deviates from the above documentation (as well as from the IPASIR standard), am I mistaken?

`Solver::val` calls the `ival` function on `External`, which is implemented as follows:

https://github.com/arminbiere/cadical/blob/2df7b7fed0f9c522fd4cdf6e88cecad4cac8a2df/src/external.hpp#L294-L306

Indeed, in case `elit` is negative and is also part of the assignment, then `res` is first set to `-eidx` (i.e. `elit`) on line 302, after which it is negated to `eidx` (i.e. `-elit`) on line 304.

**Comment by arminbiere** [comment]
It looks something is off here.  In general there was a misunderstanding between Tomas and me when we defined 'value' semantics in the IPASIR interface.  At least I thought to just return a ternary value (-1,0,1) as in PicoSAT, but then for some reason in IPASIR we defined value semantics to return for a literal 'lit' which is true 'lit' itself and otherwise if it is false its negation '-lit'.  For the CPP interface this works (even though originally it had a different semantics):
```
#include "../src/cadical.hpp"

void test_value_semantics_in_CPP_interface () {
  CaDiCaL::Solver solver;
  solver.clause (1, 2);
  solver.clause (1, -2);
  solver.clause (-1, -2);
  int res = solver.solve ();
  assert (res == 10);
  assert (solver.val (1) == 1);
  assert (solver.val (2) == -2);
  assert (solver.val (-1) == -1);
  assert (solver.val (-2) == 2);
}
```
However, this actually was not following the IPASIR semantics.  It seems now that the C functions did not follow up on that change.   As the following test case fails:
```
#include "../src/ccadical.h"

void test_value_semantics_in_C_interface () {
  auto solver = ccadical_init ();
  ccadical_add (solver, 1), ccadical_add (solver, 2),
      ccadical_add (solver, 0);
  ccadical_add (solver, 1), ccadical_add (solver, -2),
      ccadical_add (solver, 0);
  ccadical_add (solver, -1), ccadical_add (solver, -2),
      ccadical_add (solver, 0);
  int res = ccadical_solve (solver);
  assert (res == 10);
  assert (ccadical_val (solver, 1) == 1);
  assert (ccadical_val (solver, 2) == -2);
  assert (ccadical_val (solver, -1) == 1);
  assert (ccadical_val (solver, -2) == 2);
  ccadical_release (solver);
}
```
with
```
/home/biere/src/cadical/src/cadical.cpp:1014: void test_value_semantics_in_C_interface(): Assertion `ccadical_val (solver, -1) == 1' failed.
```

**Comment by arminbiere** [comment]
There is now a fix on the ccadical-val-issue-108 branch.  We will incorporate this in the next release.  For now the work-around is to not use negative literals in 'ccadical_val' or 'Solver::val'.

**Comment by m-fleury** [comment]
Fixed by the merge https://github.com/arminbiere/cadical/commit/6466809cd5a4ce32fd746250778153a781f41659 for the release 2.1.
