### ISSUE TITLE
Bug: ipasir_val should return +lit/-lit instead of +1/-1

### ISSUE THREAD

**Issue by tuzz** [arminbiere/cadical#12]
I think there's a small bug in the IPASIR interface.

As discussed via email, the PicoSAT glue code has [the correct semantics](https://github.com/biotomas/ipasir/blob/master/sat/picosat961/ipasirpicosatglue.c#L36), whereas Cadical returns +1/-1.

Thanks

**Comment by arminbiere** [comment]
Thanks, as discussed, this is a discrepancy between the old PicoSAT API which actually served as blueprint for IPASIR and the then adopted IPASIR semantics.  I fixed it in the actual 'cadical' API (thus that the ipasir_val function does not need to be changed).
