### ISSUE TITLE
hardcoded -j 12

### ISSUE THREAD

**Issue by q3k** [arminbiere/cadical#14]
Currently, cadical hardcodes `-j12` in MAKEFLAGS: https://github.com/arminbiere/cadical/blob/20e1a911c9e0060fd436aea721dd79d9f77a25ad/makefile.in#L17

This breaks builds on machines with low memory (OOM).

I would recommend fixing jobserver settings (eg. making configure generate `$(MAKE)` instead of `make -j1`.

**Comment by q3k** [comment]
FWIW, https://github.com/q3k/cadical/tree/77d42be517d99e80098bdd25df6bac9b429097cf has my fixes applied and builds fine in a container with 512MB of memory at -j2.

**Comment by arminbiere** [comment]
Fixed in latest release (is now a 'configure' option).
