### ISSUE TITLE
writing output does not work

### ISSUE THREAD

**Issue by DvonHolten** [arminbiere/cadical#16]
seems, the -o fileName option does not work. Colorful output goes to console instead.
Noticed that in the previous version already.

**Comment by DvonHolten** [comment]
shame shame shame - the output really seems to work, but not as expected: 
the (optimised?) cnf-file is written after a solution was found.
Some fumbling revealed this:
the option -o <file>  writes the formula in CNF 'as is' _at the end_ of the work.
When i set a timeout of 5 seconds, it outputs (more or less) the input-formula.
When i set a timeout of 15 seconds, it outputs a smaller formula.
When i let it solve the problem, it outputs the smallest formula - at the end, of course.

**Comment by DvonHolten** [comment]
one more thought - is it possible to start the solver with requested output and a timeout and after the timeout expires, the current state of the formula is written? 
that would be cute - it would allow to solve a problem stepwise, that is each night with a timeout of 6 hours, to be continued in the next night...

**Comment by arminbiere** [comment]
This feature is mainly there to allow CaDiCaL to be used as preprocessor.

`./build/cadical test/cnf/prime4294967297.cnf -P10 -O3 -o /tmp/simplified.cnf -d 0
`
produces a simplified CNF from the test case (14% variables left).

Adding serilisation and clone is on my TODO list already too.
