### ISSUE TITLE
Use 's UNKNOWN' or 's INDETERMINATE'

### ISSUE THREAD

**Issue by ajohnson1** [arminbiere/cadical#18]
It's not a big deal, but there used to be a suggestion [SAT competition 2011 rules](http://www.satcompetition.org/2011/rules.pdf) [SAT Competition 2002: requirements for the solvers](http://www.satcompetition.org/2004/format-solvers2004.html) that solvers output
```
s UNKNOWN
```
for an unsolved problem (for example on timeout).

Cadical outputs
```
c UNKNOWN
```
See https://github.com/arminbiere/cadical/blob/18b56ab0749974e975ee1414b0388b1d1ef0fa1a/src/cadical.cpp#L522

Admittedly, other solvers output different messages including:
```
s INDETERMINATE
```
```
c s UNKNOWN
```
so perhaps `s INDETERMINATE` is the more modern choice. 
I know the return code of 20, 10 or 0 also shows the result but the `s ` line is more permanent.

It would be nice if there was an option to write the solution to a file with `s SATISFIABLE` and `v ` with the variables for analysis later, and colourful output to the console while solving was in progress. I could do it with pipes, but it gets a bit complicated.

**Comment by arminbiere** [comment]
These are two issues actually.  I had  's UNKNOWN' with some solvers, but it does not adhere to the SAT competition output requirement and since I am (co-)organizing a competition myself (HWMCC) I know that it is best for the output to be as uniform as possible and the same for every body.  There is a clear definition of what makes up a solution (only 's' and 'v' lines) and you can just filter out the 'c' lines to get that.  Anyhow, let us keep this 'c UNKONWN'.

The reason why I have not done the second feature is that I can not make up my mind about the proper command line option, since I have already '-O[0-9]' and then the following:

  -o <output>    write simplified CNF in DIMACS format to file
  -e <extend>    write reconstruction/extension stack to file

  -s <sol>       read solution in competition output format
                 to check consistency of learned clauses
                 during testing and debugging

This new one should ideally be a short option, but the clearest one '-o' and '-s' are already gone ...

Any idea?

**Comment by arminbiere** [comment]
OK, I think

-r  read solution
-w write solution

(and remove '-s' with a deprecated warning for now)

should make sense ...

**Comment by ajohnson1** [comment]
`-r` and `-w` makes sense (and `-w` for write is also like witness).

Here is a comparison of outputs from different solvers.
The other solvers have a different format for an output file (just the numbers or SAT and then the numbers), but I can handle `s SATISFIABLE` `v 1 2 3 ... 0` in the file just fine (and it matches what is already needed for `-s` or `-r`.

As a work-around with the existing behaviour I used `cadical --colors file.cnf | tee >(grep "^[sv] " >file.out)` but that is bash specific.

|Solver|stdout SAT|stdout UNSAT|stdout INDET|file SAT|file UNSAT|file INDET|
|---|---|---|---|---|---|---|
|cadical|s SATISFIABLE|s UNSATISFIABLE|c UNKNOWN||||
||v 1 -2 -3||||||
||...||||||
||v 1001 1002 0|||||
|lingeling|s SATISFIABLE|s UNSATISFIABLE|c s UNKNOWN||||
||v 1 -2 -3|||||
||...|||||
||v 1001 1002 0||||||
|cryptominisat5|s SATISFIABLE|s UNSATISFIABLE|s INDETERMINATE|SAT|UNSAT|s INDETERMINATE
||v -1 -2 -3 .. 0|||-1 -2 ... 0
|glucose parallel|s SATISFIABLE|s UNSATISFIABLE||SAT|UNSAT||
|||||-1 -2 ... 0|
|glucose simp|s SATISFIABLE|s UNSATISFIABLE|s INDETERMINATE|1 2 3 4 ... 0|UNSAT|INDET
|sat4j|s SATISFIABLE|s UNSATISFIABLE|s UNKNOWN|
||v -1 -2 -3 -4 -5 ... 0|	

Some of the outputs from Glucose look non-standard, but I need to check which version I was looking at.

**Comment by arminbiere** [comment]
I have added the promised '-r' (now completely replaces '-s') and '-w' options to the newest release but left the output for 'UNKNOWN' as is.  Maybe it would be good to have by default SAT Competition compliance (so not using 's UNKNOWN') and with an option forcing 's UNKNOWN' (both in '<stdout>' or in the solution file if '-w' is used).

**Comment by ajohnson1** [comment]
The [Sat Competition 2022](https://satcompetition.github.io/2022/rules.html) says:
>SAT solvers must conform to DIMACS input/output requirements (see SAT Competition 2009 for details). Printing models in case of a satisfiable instance is required for all tracks expect for "no-limits". Additionally, UNSAT certificates (proofs) are required for the main tracks. 

[SAT Competition 2009](http://www.satcompetition.org/2009/) says in [SAT Competition 2009: requirements for the solvers](http://www.satcompetition.org/2009/format-solvers2009.html) :
> solution ("s " lines)
This line starts by the two characters: lower case s followed by a space (ASCII code 32).
Only one such line is allowed.
It is mandatory.
This line gives the answer of the solver. It must be one of the following answers:
>
>    `s SATISFIABLE`
    This line indicates that the solver has found a model of the formula, and in such a case, a "v " line is mandatory.
    This line must be output when the solver has found a model.
    `s UNSATISFIABLE`
    This line must be output when the solver can prove that the formula has no model.
    `s UNKNOWN`
    This line must be output in any other case, i.e. when the solver is not able to tell anything about the formula.
>
>It is of uttermost importance to respect the exact spelling of these answers. Any mistake in the writing of these lines will cause the answer to be disregarded.
Solvers are not required to provide any specific exit code corresponding to their answer.
>
>If the solver does not output a solution line, or if the solution line is misspelled, then UNKNOWN will be assumed.

so `s UNKNOWN` is permissible, but is optional.

**Comment by arminbiere** [comment]
I think some tools do not support 's UNKNOWN' (at least I remember removing the 's' and replacing it with 'c' in some of my solvers).  Unless I hear any other more compelling arguments, I will close this.
