### ISSUE TITLE
-Wdeprecated-copy warning for Random (Seed) in mobical.cpp

### ISSUE THREAD

**Issue by ajohnson1** [arminbiere/cadical#19]
Thank you for Cadical - it works well for me under Cygwin.

I upgraded my compiler and got a new compiler warning with gcc version 9.3.0 (GCC)
```
../src/mobical.cpp:2900:28: warning: implicitly-declared ‘constexpr CaDiCaL::Random& CaDiCaL::Random::operator=(const CaDiCaL::Random&)’ is deprecated [-Wdeprecated-copy]
 2900 |       random = Random (seed);
      |                            ^
In file included from ../src/internal.hpp:75,
                 from ../src/mobical.cpp:107:
../src/random.hpp:23:3: note: because ‘CaDiCaL::Random’ has user-provided ‘CaDiCaL::Random::Random(const CaDiCaL::Random&)’
```

Now this is in test code and doesn't cause any real problems but it would be nice to keep the warning flag and make the code compile cleanly.

I think the warning is saying Random has a user defined copy constructor but not an assignment operator. To a certain extent assigning a random number generator to another variable is constructing another one with the same internal state and then the two will generate the same sequence, which might be a problem.

In this bit of mobical a default random number generator is constructed and then if an explicit seed is given a new generator is constructed with the seed which replaces the old one.

Possible solutions:

In random.hpp 

1. give an explicit default assignment operator - so implying creating a copy by assignment is fine.
` Random& operator=(const Random& other) = default;`
2. remove the copy constructor?

In mobical.cpp

1. Construct the default generator, then the new seeded generator, then in both places extract the seed to a common variable. Then construct a new generator with the seed.
2. If a seed is given, adjust the seed of the default generator. `random += seed - random.seed();` This relies on the implementation of Random to give the same results.

I think the use of the generator in this bit of mobical is slightly odd - the generator is used to seed another generator for each trace run:
`trace.generate (traces, random.seed ());`
then
`random.next ();`
I think this means that if the generator had the sequence (small numbers for an example) 1,17,2,25,34,15 then the first trace.generate run would use:
1,17,2,25,34,15,...
and the second would get
17,2,25,34,15,...
and the third
2,25,34,15,...
Would this matter?

**Comment by arminbiere** [comment]
Thanks!I have internally added the explicit copy operator.  Before I was relying that the compiler by default generates it - I am not sure why there is now a warning.  In any case I can not easily compile with gcc 9 but regularly test with others (starting with some 4.X version even though C++11 is tricky on some of them and also up to 8 - same for a range of clang versions).  In the on of the next stable releases this will be fixed.

**Comment by arminbiere** [comment]
While testing  on Cygwin with GCC 9.3.0 I fixed this issue as well as another new warning.  This is now in Release 1.3.0.
