### ISSUE TITLE
Incremental usage with API: error vs. solve-status

### ISSUE THREAD

**Issue by sschnug** [arminbiere/cadical#2]
Hi,

for fun i'm writing a small [python-wrapper](https://github.com/sschnug/pycadical) and tried to add something like ```get_all_solutions()``` (where the user obviously should know what to expect; exponential-blowup).

While the API looks pretty clean/reduced at first sight, i ran into problems.

A simplified C++ example (based on examples/api/unit.cpp) would be:

```cpp

#include "../../src/cadical.hpp"
#include <iostream>
#ifdef NDEBUG
#undef NDEBUG
#endif
#include <cassert>
using namespace std;
int main () {
  CaDiCaL::Solver solver;
  solver.add (1);
  solver.add (0);

  int res = solver.solve ();
  cout << "solver.solve () = " << res << endl << flush;
  cout << "solver.val (1) = " << solver.val (1) << endl << flush;
  cout << "solver.val (2) = " << solver.val (2) << endl << flush;

  // forbid sol: in this case (maybe wrongfully) assuming deterministic behaviour
  cout << "next" << endl;
  solver.add(-1);
  solver.add(2);
  solver.add(0);
  res = solver.solve();
  cout << "solver.solve () = " << res << endl << flush;
  cout << "solver.val (1) = " << solver.val (1) << endl << flush;
  cout << "solver.val (2) = " << solver.val (2) << endl << flush;

  // forbid sol: in this case (maybe wrongfully) assuming deterministic behaviour
  cout << "next" << endl;
  solver.add(-1);
  solver.add(-2);
  solver.add(0);
  res = solver.solve();
  cout << "solver.solve () = " << res << endl << flush;
  cout << "solver.val (1) = " << solver.val (1) << endl << flush;
  cout << "solver.val (2) = " << solver.val (2) << endl << flush;

  return 0;
}

```

Which outputs:

```
solver.solve () = 10
solver.val (1) = 1
solver.val (2) = 0
next
solver.solve () = 10
solver.val (1) = 1
solver.val (2) = 1
next
*** cadical error: unsatisfied clause:
-1 -2 0
Aborted (core dumped)
```

- It seems cadical always throws an error when there is no solution in this incremental-usage
- I would have expected, it's just returning the appropriate status in ```solve()```. (If that's really the behaviour and i'm not misusing it; it's obviously less nice to wrap!)

Did i do something wrong or is this a missing feature or some explicit design-decision?
(while not familiar with the internals, i also set ```options.check = false```; but then the same solutions seem to be generated despite the clauses trying to forbid those).

**Comment by arminbiere** [comment]
Incremental use of CaDiCaL is not working yet.  So this is an unsupported feature.

**Comment by arminbiere** [comment]
The new release supports incremental solving.
