### ISSUE TITLE
Kissat vs. Cadical vs. Cadical

### ISSUE THREAD

**Issue by DvonHolten** [arminbiere/cadical#22]
here some performance data of the latest Cadical

compilation on cygwin64 worked very smooth.

execution ( on cygwin64 ) is fine. Some early results compared to cadical october 2019:
seconds, incl reading
```
kissat     Cadical    Cadical
           Oct 19     Jun 20
 640        586         788
 663         74         165
  78        135          91
 341        100         139
1307       1890        1431
```

hmmm

**Comment by arminbiere** [comment]
Are these cumulative seconds, or are you just using 5 benchmarks?

**Comment by DvonHolten** [comment]
5 different benchmark-files, wall-clock seconds for each run, --sat otherwise default-options.
interested in the files ?

**Comment by arminbiere** [comment]
Of course always ?

**Comment by DvonHolten** [comment]
the files are zipped for transport - unpack before solving

[b2005-p1-12x12c15h7-SortNet10Upd2.zip](https://github.com/arminbiere/cadical/files/4764162/b2005-p1-12x12c15h7-SortNet10Upd2.zip)
[b2005-p2-12x12c15h7-SortNet10Upd2.zip](https://github.com/arminbiere/cadical/files/4764166/b2005-p2-12x12c15h7-SortNet10Upd2.zip)
[b2005-p3-12x12c15h7-SortNet10Upd2.zip](https://github.com/arminbiere/cadical/files/4764167/b2005-p3-12x12c15h7-SortNet10Upd2.zip)
[b2005-p4-12x12c15h7-SortNet10Upd2.zip](https://github.com/arminbiere/cadical/files/4764168/b2005-p4-12x12c15h7-SortNet10Upd2.zip)
[b2005-p5-12x12c15h7-SortNet10Upd2.zip](https://github.com/arminbiere/cadical/files/4764169/b2005-p5-12x12c15h7-SortNet10Upd2.zip)

**Comment by arminbiere** [comment]
Thanks got them ...

**Comment by arminbiere** [comment]
I played with two of them, but could not get better performance.  They do shrink substantially with one round of preprocessing (with CaDiCaL) and then failed literal probing (another tool) to around 14% variables  The default configuration of CaDiCaL and Kissat are good for these.
