### ISSUE TITLE
Return code 142 with run with timeout

### ISSUE THREAD

**Issue by ajohnson1** [arminbiere/cadical#23]
Thank you for CaDiCal - generally it works well for me.

Using:
c Version 1.3.0 0b7a2b5764f845cff0b81ec16ebac20cb5cc138c
c g++ (GCC) 9.3.0 -Wall -Wextra -O3 -DNDEBUG
compiled under Cygwin64 on Windows I noticed this problem on one run where CaDiCal returned 142, instead of 10,20, or 0.

```
   t1=${SECONDS}
   ../../git/cadical/build/cadical.exe -q -t $timeout x | tee x1
   r=${PIPESTATUS[0]}
   t2=${SECONDS}
   took=$(($t2 - $t1))
   echo "For $pre returned $r in $took seconds"
```

```
For [8842/65536] returned 142 in 119 seconds
```

`timeout=120` and x is of medium size `p cnf 9399 290432` and I don't think it is unusual.
```
$ wc x
  478567  2547613 13573644 x
```

I'm doing thousands of this sort of run, and this is the only time it happened. I tried to reproduce it by running with the same cnf (should be identical, but it was rebuilt with the same parameters) and CaDiCal confirmed it was unsatisifiable in about 77 seconds, but the machine was running other programs when the failing run occured, so may have been under more load.

There were no messages from stdout in x1, or on stderr.

Perhaps the alarm signal popped early, though simulating this with `kill -14` gives
```
Alarm clock
```
with `-q` or
```
c raising signal 14 (SIGALRM)
Alarm clock
```
without `-q`.

Perhaps there is a race condition at the end where the signal handler is removed before the timer stops.

If you can't see a problem in the code from this information we may have to close this as unreproducible.

**Comment by ajohnson1** [comment]
I've managed to reproduce something similar by having a CNF which takes just under 3 seconds to solve on my machine, then running it in a loop with `-t 3` until the return code is not 10 or 0. After a few minutes I got a failure.

The output was:
```
c
c --- [ resources ] ----------------------------------------------------------
c
c total process time since initialization:         2.81    seconds
c total real time since initialization:            3.01    seconds
c maximum resident set size of process:           14.77    MB
c
c --- [ shutting down ] ------------------------------------------------------
c
c exit 10
./loop.sh: line 9: 24810 Alarm clock             cadical --sat -t 3 sted5.sat
Done 142
```

**Comment by arminbiere** [comment]
Thanks, I think I had similar problems with Kissat/Tissat and automatically testing the timeout, as well as fuzzing with a hard code time limit (also of 3 seconds), but I do not recall what fixed it (and maybe after all it is a Cygwin issue).   I will have a look.

**Comment by ajohnson1** [comment]
You could try adding `::alarm (0);`to `Signal::reset_alarm ()` before restoring the original signal handler.
That might stop the alarm triggering later and calling the original default signal handler, which was nicely saved and restored, but might cause a process termination if called during shutdown.

That seems to fix it for me. It was more reproducible if I put a sleep(2) in `cadical main()` after the destructor of `CaDiCaL::App app` has run.

**Comment by arminbiere** [comment]
I have added an 'alarm (0)' to the application code before resetting signals and this should fix things.  I have tested it by (parallel) file based fuzzing in combination with a time-out of 3 seconds (what was my main fuzzing approach for Kissat) and I could not trigger the problem I described anymore and thus hope that this fixes this issue too.

**Comment by ajohnson1** [comment]
Confirmed as fixed - without the alarm(0) it failed after 200 or so iterations, with it I got over 1000 runs without a problem. Thank you.
