### ISSUE TITLE
How to Cite if We are Using Your Tool?

### ISSUE THREAD

**Issue by hadipourh** [arminbiere/cadical#25]
Dear Armin,

Thank you very much for creating this useful SAT solver. Let me know please how to cite this tool if we are using it in our publications. Thanks for your time. 

Kind regards,
hosein

**Comment by arminbiere** [comment]
For now just use the latest SAT Competition Proceedings (say for this year):

@inproceedings{BiereFazekasFleuryHeisinger-SAT-Competition-2020-solvers,
  author    = {Armin Biere and Katalin Fazekas and Mathias Fleury and Maximillian Heisinger},
  title     = {{CaDiCaL}, {Kissat}, {Paracooba}, {Plingeling} and {Treengeling} Entering the {SAT Competition 2020}},
  pages     = {51--53},
  editor    = {Tomas Balyo and Nils Froleyks and Marijn Heule and Markus Iser and Matti J{\"a}rvisalo and Martin Suda},
  booktitle = {Proc.~of {SAT Competition} 2020 -- Solver and Benchmark Descriptions},
  volume    = {B-2020-1},
  series    = {Department of Computer Science Report Series B},
  publisher = {University of Helsinki},
  year      = 2020,
}

I will keep this issue for adding it to the top-level README.

**Comment by hadipourh** [comment]
Thanks!

**Comment by arminbiere** [comment]
Added BibTeX entry to the top README.md.
