### ISSUE TITLE
Spurious quadratic loop in Internal::init_vars

### ISSUE THREAD

**Issue by tautschnig** [arminbiere/cadical#28]
Indentation suggests that https://github.com/arminbiere/cadical/blame/master/src/internal.cpp#L157 is a loop without body, which of course means that the statements below are executed upon each loop iteration. This results in a quadratic loop, repeatedly performing `assert (ptab[i] == -1);`.

Maybe some other property was intended to be asserted, else line 157 should just be removed.

(`git blame` is no help, those lines were all added in the same commit.)

**Comment by arminbiere** [comment]
This was already spotted by a collaborator last August and will be fixed in the next release (I use this public git repository only for releases and bug fixes to releases but keep development non-public and without revision history).

**Comment by arminbiere** [comment]
Fixed in the latest release.
