### ISSUE TITLE
Long execution time

### ISSUE THREAD

**Issue by sbelodon** [arminbiere/cadical#29]
Hello, your solver are great, but can't solution for file in 24 hours. 
Maybe it's needed to turn on some settings?
I use core i7 computer

[test2.cnf.zip](https://github.com/arminbiere/cadical/files/5838231/test2.cnf.zip)

**Comment by a1880** [comment]
Looking at the statistics of your test2 CNF, it is not surprising to have a long runtime:

```
Variables:  134,781 
Literals: 1,952,208 (986,453 negative, 965,755 positive)
Clauses:    648,806
Clause length histogram:
 1: 12
 2: 51,552
 3: 540,134
 4: 57,098
 9: 4
33: 4
65: 2


```

**Comment by sbelodon** [comment]
can you predict how long it'll be solved?

**Comment by a1880** [comment]
No. SAT solving has a bit of black magic in this respect.

**Comment by arminbiere** [comment]
Treengeling took (on a slow 12 core machine):

c cleaning up after 153 rounds
c 
c 153 rounds, 3012 nodes (1125 max), 64396 threads (24 max)
c 97186 avg clim, 82 incs, 42 decs, 8 forced, 2 simp
c 
c 670120.22 wall clock time, 14473682.06 process time
c 90% utilization for 23 + 1 worker threads on 24 cores
c 
c started 2 additional parallel solver instances
c 1182 units consumed 264% of 448 produced
c 2001 leaf clauses consumed 100% of 2001 produced
c 
c 2327621769 conflicts, 3473 conflicts per second
c 12047871569 decisions, 17979 decisions per second
c 9347838918115 propagations, 13.9 million propagations per second
c 
c 2665 tree-based look-ahead 89% out of 3011 look-aheads
c 346 relevance based look-ahead 11% out of 3011 look-aheads
c 
c    3011   5% lookaheads       173.54 seconds    0%
c    3011   5% splits           114.51 seconds    0%
c   28495  44% simplifications 44456.64 seconds    7%
c   29879  46% searches        625367.25 seconds   93%
c ======================================================
c   64396 100% scheduled jobs  670120.22 seconds, 36819 MB
c 
c result 10

**Comment by sbelodon** [comment]
Thanks!
