### ISSUE TITLE
bug in limit.cpp

### ISSUE THREAD

**Issue by fbacchus** [arminbiere/cadical#30]
Line 63 of limit.cpp:
    inc.decisions = stats.decisions + l;

should be
      inc.decisions = l;

===
shows up only on 2nd and onwards calls to the sat solver.

**Comment by arminbiere** [comment]
Thanks, there is indeed a discrepancy how conflicts and decision limits are treated.  For conflicts it is your proposed fix. However, I tend to argue that you want actually the version where you add a limit to the current number of decisions (so keeping in your case the version

`    inc.decisions = stats.decisions + l;`

and fixing the conflict limit version instead to

`  inc.conflicts = stats.conflicts + l;`

**Comment by arminbiere** [comment]
Fixed in the latest release 1.4.0.
