### ISSUE TITLE
src/makefile is a broken link before running configure

### ISSUE THREAD

**Issue by recoules** [arminbiere/cadical#36]
The symlink `src/makefile` point to the non-existent `makefile` file.
Thus, it prevents `dune` build system, that copies all the files before starting to run any command, to work correctly.

Yet I am not sure that this link is useful since the compilation perfectly work without it.
Would it be possible to remove it from the source tree?

**Comment by krobelus** [comment]
(context: https://github.com/recoules/ocaml-bitwuzla/)

Yeah I think it's fair to have `./configure` create the symlink. Though I find `dune`'s behavior questionable.

**Comment by recoules** [comment]
> Though I find dune's behavior questionable.

Well,  Dune is not initially intended to compile complex C libraries and it can certainly be improved (https://dune.readthedocs.io/en/stable/foreign-code.html#foreign-build-sandboxing).

> Yeah I think it's fair to have ./configure create the symlink.

Yet, the fact that the project compile fine without this symlink make me think it could be simply removed.

**Comment by recoules** [comment]
@arminbiere @m-fleury Any thought on this? It should be easy to fix.

**Comment by m-fleury** [comment]
This will be addressed in the next release.

**Comment by arminbiere** [comment]
The reason for having the symlink in the 'src' directory is to be able to issue 'make' from there and that is really helpful to have if you work from the command line, like I do, so I want to keep it.  So my proposal would be to have 'configure' generate the link and 'make clean' remove it.

**Comment by recoules** [comment]
That is fine for me as long as it is no longer present in a fresh `git clone`.

**Comment by recoules** [comment]
@arminbiere Do you think you could push a fix soon? Because it breaks all my CI and I expect it to be a matter of minutes to fix. I do not want to create a fork only for this.

**Comment by arminbiere** [comment]
Fixed in latest release (rel-1.4.1).

**Comment by recoules** [comment]
Thank you, it works well
