### ISSUE TITLE
Compilation failure on archlinux

### ISSUE THREAD

**Issue by recoules** [arminbiere/cadical#37]
It sounds like the include files are slightly different in `archlinux`.
```bash
in file included from ../src/reap.cpp:1:
../src/reap.hpp:15:10: error: ‘size_t’ does not name a type
```
I solved it by swapping the order of include in `reao.cpp`: I put `#include "reap.hpp"` after the others:
```c++
#include<cstring>
#include<cassert>
#include <climits>
#include "reap.hpp"
```

**Comment by m-fleury** [comment]
Fixed by #32. So will be addressed in the next release.

**Comment by recoules** [comment]
Ok sorry for duplicate.

**Comment by arminbiere** [comment]
Should work in the new release.

**Comment by recoules** [comment]
I confirm it works, thank you
