### ISSUE TITLE
Running on multi-thread platform

### ISSUE THREAD

**Issue by lhsxb8** [arminbiere/cadical#45]
Hi!
I need to solve lagre-scale cnf problems, but when I use cadical it only run on one thread. 
(I have tried to find any method on '--help'
Does it support multi-thread or multi-processors programming?

Best regards.

**Comment by a1880** [comment]
[Gimsatul](https://github.com/arminbiere/gimsatul) actually does support multiple threads. Cadical is single-threaded.

**Comment by lhsxb8** [comment]
It seems like when the number of clauses is less than 1000, the Gimsatul slover (with 8 threads) is much faster than Cadical. 
But when it's bigger than 15000, Cadical still faster than Gimsatul, it's surprising.

**Comment by arminbiere** [comment]
Can you share the CNF (maybe privately)? In any case SAT solving is rather non-deterministic in terms of performance even though solvers became much more robust in this regard recently.
