### ISSUE TITLE
mmap fails and its failure isn't reported

### ISSUE THREAD

**Issue by yurivict** [arminbiere/cadical#48]
[here](https://github.com/arminbiere/cadical/blob/master/src/mobical.cpp#L2614)

**Comment by yurivict** [comment]
The fd argument has to be set to -1.

This is a bug in Linux that it accepts fd=0 for anonymous mmaps.

**Comment by arminbiere** [comment]
Thanks will fix in the next major release.

**Comment by arminbiere** [comment]
Fixed on main branch with release 1.5.4 too.
