### ISSUE TITLE
GCC warns about comparison of `this` to `NULL`

### ISSUE THREAD

**Issue by tautschnig** [arminbiere/cadical#54]
We received the following [bug report in CBMC](https://github.com/diffblue/cbmc/issues/7725): 

```
solver.cpp:259:3: error: ‘nonnull’ argument ‘this’ compared to NULL [-Werror=nonnull-compare]
```

With more recent CaDiCaL versions this is line 261, but the issue persists. I believe this line in the definition of `TRACE` should just be removed.

**Comment by arminbiere** [comment]
The check has been commented out in our internal version in February and with the merge into the master branch and release 1.5.4 this should be fixed now (line 251).
