### ISSUE TITLE
Cadical 1.6.0 MS VC++ breaks for --shrink > 0

### ISSUE THREAD

**Issue by a1880** [arminbiere/cadical#57]
I compiled Cadical 1.6.0 in three flavors:
with MS VC++ 2022, with MSYS2 MinGW 64 and with Windows WSL2 Ubuntu g++ 11.3.0.

The MS VC++ binary stops with an assertion violation 
(cf. observation by [deiruch](https://github.com/deiruch/cadical/commit/1d9c13cebce70d3feb37ffbada9a1f8018922b38))

`line 226 of shrink.cpp:  assert (v.reason);`

As a workaround, I can use `--shrink=0` as commandline parameter.

The other two binaries don't exhibit this problem.

Greetings,

Axel Kemper

**Comment by arminbiere** [comment]
Oh well, I guess this is a Microsoft compiler issue then (the other two Windows builds
use 'gcc' I assume).  We are busy continuing to merge our SAT papers code (LRAT is next)
then we will have a look at this.

**Comment by arminbiere** [comment]
We  are still short of being able to test MS VC++ compilation, so will keep this open.

**Comment by sfiruch** [comment]
FYI: I can no longer reproduce this problem with my MSVC-compiled Windows port.

**Comment by arminbiere** [comment]
Thanks, then I close this.
