### ISSUE TITLE
[Release 1.7.0] Question re: zero-side array in `LratBuilderClause`

### ISSUE THREAD

**Issue by miquelramirez** [arminbiere/cadical#59]
Hello,

I just checked out the latest release and got a bunch of warning messages with g++ 11.3.0 like the following:

```
lratchecker.hpp:27:16: warning: ISO C++ forbids zero-size array ‘literals’ [-Wpedantic]
   27 |   int literals[0]; // 'literals' of length 'size'
      |                ^
```

What is the rationale for defining the `literals` field of `LratBuilderClause` in this fashion? is there any material difference when changing this to an `int*` declaration? 

Thanks!

**Comment by a1880** [comment]
The zero-size array actually does not consume any memory.
It is therefore possible to calculate the size of a `struct LratCheckerClause` for `n` literals 
as

`sizeof(struct LratCheckerClause) + n * sizeof(int)`

You can see the size difference of 8 bytes in [godbolt.org](https://godbolt.org/z/5cM1Ee5nM).

**Comment by miquelramirez** [comment]
Hello Alex,

thank you for your response. The documentation for this feature of  [GCC](https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html). I see also that `clang` and `msvc` do not complain about zero-length arrays and seem to support them without complaints.

The documentation also suggests that GCC would prefer to replace this idiom with flexible arrays (e.g. `int literals[]`). Quoting from the docs above:

> The preferred mechanism to declare variable-length types like struct line above is the ISO C99 flexible array member, with slightly different syntax and semantics:
> - Flexible array members are written as contents[] without the 0.
> - Flexible array members have incomplete type, and so the sizeof operator may not be applied. **As a quirk of the original implementation of zero-length arrays, sizeof evaluates to zero**.
> - Flexible array members may only appear as the last member of a struct that is otherwise non-empty.
> - A structure containing a flexible array member, or a union containing such a structure (possibly recursively), may not be a member of a structure or an element of an array. (However, these uses are permitted by GCC as extensions, see details below.)

The last clause may be problematic, I haven't checked the uses of the two data structures using this feature of C99 (?).

**Comment by a1880** [comment]
Yes. There might be more modern or idiomatic _C++_ ways to allocate structures with dynamic array members.
But this one has been used sucessfully in _C_ for decades.
It is simple and does not require extra memory.

In lines 33 and 34 of `lratchecker.cpp`, you find:

```
  const size_t bytes = sizeof (LratCheckerClause) + size * sizeof (int);
  LratCheckerClause *res = (LratCheckerClause *) new char[bytes];

```

**Comment by miquelramirez** [comment]
Hello again,

With all due respect, I am unsure what is the relevance of practices in C (or C99 from the looks of it) to a C++ library like `cadical`. Storing `void*` into `int` was also successfully used for decades until it was not. This is the reason why `gcc` emits a warning when one compiles in "strict" mode (e.g. `-pedantic` flag on). At some point in the future, someone will look at the compiler code wanting to do a refactoring and will say: I am done with maintaining this zero-array length backward compatibility support, it is the flexible array way or the highway.

I do see the space advantage but I also see that these structs are no longer POD, and copy via `=` is non-trivial as it requires that the left-hand side has been allocated in the same way as the right-hand side. The code in `lratbuilder.cpp` resorts to using pointers to these structs, which seems to me to weaken a bit the case of memory being saved (for every entry in the array `reasons` of `LratBuilder` we have a 64-bit pointer anyways). I don't see it being a very good thing for cache locality either.

I wonder what would a proper C++ solution to the problem of optimizing memory in this way would be. 

In any case, now I have full understanding of the rationale for this construct.
