### ISSUE TITLE
Minimal satisfying assignment

### ISSUE THREAD

**Issue by amatuag** [arminbiere/cadical#69]
Hi,

This is not an issue but a question about finding a minimal model for a satisfiable query. It is like a set cover problem and a brute force solution is possible after a model is returned but I was curious if there is a more elegant way.

Say  z = (a v b) /\ (b v c). This formula can just be satisfied with b = True and (a,c) are essentially don't cares. I hope my question makes sense.

**Comment by a1880** [comment]
You might find [this paper](https://asa.iti.kit.edu/downloads/m.iser_c.sinz_m.taghdiri_sat2013.pdf) from 2013 helpul.
Markus Iser, Carsten Sinz, Mana Taghdiri: Minimizing Models for Tseitin-Encoded SAT Instances

**Comment by amatuag** [comment]
Thanks. This looks like what I wanted.
