### ISSUE TITLE
External propagators only notified if LOGGING is enabled

### ISSUE THREAD

**Issue by deiruch** [arminbiere/cadical#70]
PVS Studio (https://pvs-studio.com/en/order/for-students/#IDD159822EC6) found this potential problem:

1. `int reassigned = 0;` on line 105
2. Reassigned only incremented if LOGGING is disabled:
```c
#ifdef LOGGING
      reassigned++;
#endif
```
3. `reassigned` is checked to determine if propagators should be notified:
```c
  if (reassigned) {
    notify_assignments ();
  }
```

https://github.com/arminbiere/cadical/blob/e7369b4b04fafe8b4b139d5e181528f5006d0816/src/backtrack.cpp#L159C27-L159C27

# Proposed fix
Remove the `#ifdef LOGGING` on line 137.

**Comment by kfazekas** [comment]
Thanks for the finding, I will take a look at it.

**Comment by arminbiere** [comment]
Fixed on development and should go into the next release 1.9.2.
