### ISSUE TITLE
`Internal::promote_clause` will never keep glue in tier1

### ISSUE THREAD

**Issue by deiruch** [arminbiere/cadical#72]
PVS Studio (https://pvs-studio.com/en/order/for-students/#IDD159822EC6) found this potential problem.

The `Internal::promote_clause` function first checks, and aborts if `c->keep` is true.
- The if statement on line 163 could be simplified, the first part will always be true
- The if statement on line 172 will always be false.

Not sure if this is intended or  a logic error.

https://github.com/arminbiere/cadical/blob/e7369b4b04fafe8b4b139d5e181528f5006d0816/src/clause.cpp#L154-L180C2

**Comment by arminbiere** [comment]
The promotion policy is complicated and better spelled out precisely, in particular if it is changed this defensive code is better (putting assertions into the cases is an alternative).  For instance it is safe to remove lines 156 and 157.  Then the stats would also count improved glues in (before and after) tier1 clauses.  So I consider it better to keep this as is.
