### ISSUE TITLE
Confusing code: `cubes.status` set twice (?)

### ISSUE THREAD

**Issue by deiruch** [arminbiere/cadical#73]
PVS Studio (https://pvs-studio.com/en/order/for-students/#IDD159822EC6) found this potential problem.

`cubes.status` is set twice, in immediate succession. `res` should be 20, so probably no problem - but it's odd nonetheless.

https://github.com/arminbiere/cadical/blob/e7369b4b04fafe8b4b139d5e181528f5006d0816/src/lookahead.cpp#L429

**Comment by arminbiere** [comment]
Looks redundant, but not harmful.  Also 'lookahhead' is not used much.

**Comment by arminbiere** [comment]
Fixed on development and thus in the upcoming release 1.9.2
