### ISSUE TITLE
`justified` and `todo_justify` not updated as intended

### ISSUE THREAD

**Issue by deiruch** [arminbiere/cadical#74]
PVS Studio (https://pvs-studio.com/en/order/for-students/#IDD159822EC6) found this potential problem.

The for loops here don't do anything, because b is passed by value. The assignment operates on `b`, but not on the values in the vectors:
https://github.com/arminbiere/cadical/blob/e7369b4b04fafe8b4b139d5e181528f5006d0816/src/lratbuilder.cpp#L647-L650

**Comment by florianpollitt** [comment]
Thank you for posting this issue. It will be fixed in the next release. Fortunately, if this can lead to a bug only when using the option externallrat, which is not advised, and only exists because it was implemented as a stepping stone to generating lrat proofs from CaDiCaL directly.
