### ISSUE TITLE
External propagator assert failure

### ISSUE THREAD

**Issue by BrunoDutertre** [arminbiere/cadical#79]
cadical 1.9.0 or 1.9.1 can fail when an external propagator produces a
reason clause that simplifies to a unit clause at level 0.

This [test.cpp](https://github.com/arminbiere/cadical/files/13677670/test.cpp.txt) triggers this bug.

When compiling it and linking with a debug build of Cadical, it will fail with:
```
./test
Assertion failed: (level), function add_new_original_clause, file clause.cpp, line 481.
Abort
```

This causes a cvc5 regression test to fail when cvc5 is linked with  cadical 1.9.0 or 1.9.1.

**Comment by kfazekas** [comment]
Thanks for the finding, we will investigate it.

**Comment by arminbiere** [comment]
Assertion does not show up anymore on the development branch.
The test case results in an infinite loop as the user propagator continues
propagating literal '1' forever.  Thus this test case does not terminate.
I mark this as closed nevertheless.
