### ISSUE TITLE
make test fails on MacOS

### ISSUE THREAD

**Issue by BrunoDutertre** [arminbiere/cadical#8]
@arminbiere 

Shell script  ``extend-solution.sh`` does not work on MacOS (because sed doe
not interpret \n as new line).

**Comment by arminbiere** [comment]
Had this problem before with other sed scripts and feared that something like
that might show up.  But I am currently not able to test on MacOS.

**Comment by arminbiere** [comment]
Replaced this part in the script by an awk script which seems to be more portable.
