### ISSUE TITLE
Assertion failure in disconnect_external_propagator

### ISSUE THREAD

**Issue by BrunoDutertre** [arminbiere/cadical#80]
If you connect an external propagator to cadical then disconnect it without adding any observed variable,
the call to `disconnect_external_propagator` will abort with an assertion failure:
```
Assertion failed: ((size_t) max_var + 1 == is_observed.size ()), function reset_observed_vars, file external.cpp, line 394.
Abort
```

Here's a minimal example that causes this: [test2.cpp](https://github.com/arminbiere/cadical/files/13678201/test2.cpp.txt).
(I'm using cadical-1.9.1).

**Comment by arminbiere** [comment]
Thanks, works now  on development branch and thus should for the next upcoming release 1.9.2 too.
