### ISSUE TITLE
Bug in handling of assumptions

### ISSUE THREAD

**Issue by BrunoDutertre** [arminbiere/cadical#81]
The ILB for assumption code (in commit 618d2bce9a6b2f49fdc7e84dce526c9d5d6c55a0) does not always work.

With an external propagator, it's possible to create new variables and use them as assumptions.
In this case, the code in `sort_and_reuse_assumptions` will do nothing because `max_level` will be 0,
and `size` will be 1.

Here's an example that triggers this bug: [test3.cpp](https://github.com/arminbiere/cadical/files/13681147/test3.cpp.txt).
The relevant fragment is this:
```
  // assert c or d
  solver->add(c);
  solver->add(d);
  solver->add(0);

  // assume -c and -d then solve
  solver->assume(-c);
  solver->assume(-d);
  int res2 = solver->solve();
  assert(res2 == 20);
```
The assertion fails because the assumptions are ignored.

Disabling the `ilbassumptions` option does not work either, since `Internal::assume` does not take this option  into account. Here's a variant of `test3.cpp` that fails with the option disabled: [test4.cpp](https://github.com/arminbiere/cadical/files/13681173/test4.cpp.txt)

**Comment by m-fleury** [comment]
Thanks for reporting. We also found this one and fixed it on the development branch (https://github.com/arminbiere/cadical/commit/e3e1a80a9fd247e2a5cb555249e199ce2dd16b2d).

It should be fixed in the next release (current plane is do it soon).

Thanks!

**Comment by BrunoDutertre** [comment]
OK. Thanks. This commit is what I was looking for 2779488a41cc2c874e0efe2c4a5b2e4d3a4c3fa7.

**Comment by arminbiere** [comment]
It is fixed on the development branch and thus will also in the next release.
