### ISSUE TITLE
Statistics Bug Report

### ISSUE THREAD

**Issue by baselkhouri** [arminbiere/cadical#82]
It could be that in method `Internal::new_clause`, `stats.added.total` is incremented twice unintentionally (src/clause.cpp at lines 98 and 131).
 
https://github.com/arminbiere/cadical/blob/3d346f7a73080b276ae26fc2d15845747371fa1e/src/clause.cpp#L98C4-L98C19
https://github.com/arminbiere/cadical/blob/3d346f7a73080b276ae26fc2d15845747371fa1e/src/clause.cpp#L131

Thanks in advance,

**Comment by m-fleury** [comment]
That statistics is not used anywhere for the behavior of the solver.

Thanks!
