### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by BrunoDutertre** [arminbiere/cadical#9]
Another MacOS problem. You need to give -std=c++11 (or -std=c++0x) to
the compiler (this is Apple Clang++ 10.0.1) otherwise it will produce a lot
of warnings like this:

```
warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
```

**Comment by arminbiere** [comment]
This one should be caught by the configure script.   There is an explicit
test (the ''feature=configure-requires-c++0x').  I will try to get travis working
for MacOS again.

**Comment by arminbiere** [comment]
I added -Werror and -pedantic to the feature test in configure, which now forces
'-std=c++0x'  on the 10.2 osx build on travis.    I consider this solved now.
