### ISSUE TITLE
External propagator is not notified about new level

### ISSUE THREAD

**Issue by trewes** [arminbiere/cadical#92]
In my program, it sometimes happens that the connected external propagator is notified of a backtrack to level 0, then immeadiately after, it is notified of a backtrack to level 2. It is not notified of any new assignments or of a new decision level inbetween. This happens for me both with the main (1462073) and development (4b1a55d) branch on several of my instances. I don't really know how I could produce a minimal example of this.

I've tried following Cadical to see what happens inbetween the two backtracks. The first backtrack to level 0 happens in `Internal::elim`, in the call to `backtrack ();`right at the top. https://github.com/arminbiere/cadical/blob/146207318796f094dcded87349a64f0c6927309e/src/elim.cpp#L988
A  few lines below, `subsume (update_limits);` is called, 
https://github.com/arminbiere/cadical/blob/146207318796f094dcded87349a64f0c6927309e/src/elim.cpp#L1007
which calls different vivify functions `Internal::vivify` and `Internal::vivify_round` until in `Internal::vivify_clause` the function `vivify_assume (-lit)` is called,
https://github.com/arminbiere/cadical/blob/146207318796f094dcded87349a64f0c6927309e/src/vivify.cpp#L853
 which increases the internal level (in my cases it is called several times until the level is 3). This seems to not be communicated to the external propagator and in the next block, still in `Internal::vivify_clause`, `backtrack (level - 1);` is called which does notify the external propagator of a backtrack to level 2. 
https://github.com/arminbiere/cadical/blob/146207318796f094dcded87349a64f0c6927309e/src/vivify.cpp#L901

I don't think this is the desired behaviour as we only want to backtrack to lower decision levels, and either the new levels should be communicated to the connected external propagator or the backtrack should not be communicated at that point? 
It might be that something is very wrong in my code as well, but I thought it might be good for you to have a look whether there should actually be a notification to the external propgator in there; or you might have an idea what could go wrong in my code to cause Cadical to not notify in the right order. 
I can get around this issue for me by faking the notifications with calling `notify_new_decision_level()` myself but I don't trust that this will not cause other problems.

**Comment by kfazekas** [comment]
Thank you for your thorough remark, this is indeed a bug in the released version.
We are currently working on some refinements of the propagator where this bug we already fixed (commit 0ba2ef7 on ipasirup-refinements branch). Once these changes get into release, hopefully your problem will be solved as well. Thanks again for your finding!

**Comment by trewes** [comment]
Ah that is good to know, thank you! I'm glad you are already aware of it, I look forward to the release then.

**Comment by alexeyignatiev** [comment]
@kfazekas, is my understanding correct that the bug is not present in the version 1.9.4?

**Comment by alexeyignatiev** [comment]
Thanks, @trewes! Interestingly, it did not manifest itself in my case...

**Comment by trewes** [comment]
Hello @kfazekas, I encountered another problem that seems to also be fixed on the ipasirup branch so I am considering using that version instead. For that I wanted to ask whether the changes to the function signatures of the callbacks will stay as they are right now or are likely to change in the future. 
Additionally, since the callback is now `virtual void notify_assignment (const std::vector<int>& lits) = 0;`, are fixed literals not communicated to the external propagator anymore?

**Comment by kfazekas** [comment]
Hi @trewes, yes, the function signature changes are meant to stay so (so the notifications are batched and no separate fixed flag is passed anymore).
About the fixed literals: The propagator still communicates the fixed literals, but it does it in the same way as with any other assignments. So, for example, if a literal gets fixed on a higher decision level, the propagator will notify about its assignment, and upon backtracking will notify about its un-assignment and then re-assignment. It means that if you do not care for fixed assignments, the external propagator will take care of their notifications such that they end up assigned on your side after backtracking and you have nothing to do.
In case you care about fixed assignments and use them to simplify your side of the problem, you can additionally connect your ExternalPropagator as a 'FixedAssignmentListener' (https://github.com/arminbiere/cadical/blob/b3b2c85964b5eb2482c66e7dcb1efb68a54e0dbb/src/cadical.hpp#L1125) which gets notified eagerly upon every fixed assignments (it is independent from the propagator, so it notifies not just observed variables!).  In case you use these listener notifications, be prepared to ignore the unassignment and reassignment notifications of the propagator about these variables.

**Comment by trewes** [comment]
Great, thank you for the information! 
Good to know about the fixed literals, I have just been doing these reassignment after backtracking myself so it will be nice to not have to take care of that anymore.

**Comment by agriggio** [comment]
Hi, just to say that I also encountered the bug described here in my experiments on trying to use the external propagator feature. I switched to the `ipasirup-refinements` branch but I get the same problem... (still during vivification)

**Comment by m-fleury** [comment]
This should be fixed in the new 2.1 release. If not, please open a new issue.
